package com.stockquant.server.agent.marketfacts;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.stockquant.server.agent.backtest.BacktestCanonicalHashService;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.AssuranceLevel;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.CorporateActionType;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.FactType;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.FieldQualification;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.MarketFieldSemantic;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.MarketFieldUnit;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.QualifiedMarketField;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.RevisionQualification;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.RunNamespace;
import com.stockquant.server.agent.marketfacts.MarketFactProviderModels.UsageQualification;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.AdjustmentFactorObservation;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.BatchLineage;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.CorporateActionObservation;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.FactEnvelope;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.FactorPredecessor;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.QfqAsOfResult;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.QfqSourceIdentities;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.RawDailyBarObservation;
import com.stockquant.server.agent.marketfacts.PitMarketFactModels.TradingCalendarObservation;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyCollection;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Executes every committed QFQ golden scenario through the Java-authoritative
 * engine. The fixture contains fixed inputs and fixed expected canonical
 * results; expected hashes are never generated by this test.
 */
class QfqAsOfEngineGoldenVectorTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final JsonNode FIXTURE = loadFixture();
    private static final PitMarketFactsCanonicalService CANONICAL =
            new PitMarketFactsCanonicalService(
                    MAPPER, new BacktestCanonicalHashService(MAPPER));

    static Stream<Arguments> scenarios() {
        List<Arguments> result = new ArrayList<>();
        FIXTURE.path("scenarios").forEach(scenario -> result.add(
                Arguments.of(
                        scenario.path("id").asInt(),
                        scenario.path("name").asText(),
                        scenario)));
        return result.stream();
    }

    @ParameterizedTest(name = "{0}: {1}")
    @MethodSource("scenarios")
    void executesCommittedScenario(
            int id,
            String name,
            JsonNode scenario
    ) {
        assertEquals(id, scenario.path("id").asInt());
        assertEquals(name, scenario.path("name").asText());
        JsonNode defaults = FIXTURE.path("defaults");
        JsonNode input = scenario.path("input");
        Instant cutoff = Instant.parse(input.path("knowledgeCutoff").asText());
        LocalDate requestTradeDate = LocalDate.parse(
                resolveText(input, defaults, "requestTradeDate"));
        String sourceCode = resolveText(input, defaults, "sourceCode");
        String symbol = resolveText(input, defaults, "symbol");
        String exchange = resolveText(input, defaults, "exchange");
        QfqSourceIdentities identities = identities(input, defaults);

        List<RawDailyBarObservation> raw = observations(
                input.path("rawObservations"),
                node -> raw(node, input, defaults, sourceCode, identities));
        List<AdjustmentFactorObservation> factors = observations(
                input.path("factorObservations"),
                node -> factor(node, input, defaults, sourceCode, identities));
        List<TradingCalendarObservation> calendars = observations(
                input.path("calendarObservations"),
                node -> calendar(node, input, defaults, sourceCode, identities));
        List<CorporateActionObservation> actions = observations(
                input.path("corporateActionObservations"),
                node -> action(node, input, defaults, sourceCode, identities));
        List<FactorPredecessor> predecessors = observations(
                input.path("factorPredecessors"),
                node -> predecessor(
                        node, input, defaults, sourceCode, identities));

        List<RawDailyBarObservation> selectedRaw = selectVisible(
                raw, cutoff, RawDailyBarObservation::tradeDate);
        List<AdjustmentFactorObservation> selectedFactors = selectVisible(
                factors, cutoff,
                AdjustmentFactorObservation::factorEffectiveTradeDate);
        List<TradingCalendarObservation> selectedCalendars = selectVisible(
                calendars, cutoff, TradingCalendarObservation::calendarDate);
        List<CorporateActionObservation> selectedActions = selectVisible(
                actions, cutoff, CorporateActionObservation::sourceActionId);

        PitMarketFactRepository repository = mock(PitMarketFactRepository.class);
        Optional<TradingCalendarObservation> effective =
                selectedCalendars.stream()
                        .filter(TradingCalendarObservation::open)
                        .filter(item -> !item.calendarDate().isAfter(
                                requestTradeDate))
                        .max(Comparator.comparing(
                                TradingCalendarObservation::calendarDate));
        when(repository.findEffectiveTradeDate(
                anyString(), anyString(), anyString(), any(), any()))
                .thenReturn(effective);
        when(repository.findRawBarsAsOf(
                anyString(), anyString(), anyString(), anyString(),
                any(), any(), anyInt()))
                .thenReturn(selectedRaw);
        when(repository.findOpenCalendarAsOf(
                anyString(), anyString(), anyString(), any(), any(), any()))
                .thenReturn(selectedCalendars.stream()
                        .filter(TradingCalendarObservation::open)
                        .toList());
        when(repository.findFactorsAsOf(
                anyString(), anyString(), anyString(), any(), any(), any()))
                .thenReturn(selectedFactors);
        when(repository.findActionsAsOf(
                anyString(), anyString(), anyString(), any(), any(), any()))
                .thenReturn(selectedActions);
        when(repository.findFactorPredecessors(anyCollection()))
                .thenAnswer(invocation -> {
                    Collection<Long> ids = invocation.getArgument(0);
                    return predecessors.stream()
                            .filter(item -> ids.contains(item.observationId()))
                            .toList();
                });
        when(repository.findBatchLineage(anyCollection()))
                .thenAnswer(invocation -> {
                    Collection<Long> ids = invocation.getArgument(0);
                    return ids.stream()
                            .map(ignored -> batchLineage(defaults, sourceCode))
                            .toList();
                });

        QfqAsOfResult actual = new QfqAsOfEngine(repository).calculate(
                symbol, exchange, sourceCode, identities,
                requestTradeDate, cutoff);
        JsonNode projected = project(actual);
        JsonNode expected = scenario.path("expectedCanonicalResult");
        String expectedHash =
                scenario.path("expectedCanonicalHash").asText();

        assertFalse(expectedHash.isBlank());
        assertFalse("PLACEHOLDER".equals(expectedHash));
        assertTrue(expectedHash.matches("[0-9a-f]{64}"));
        assertEquals(expected, projected);
        assertEquals(expectedHash, CANONICAL.hash(projected));
    }

    private static JsonNode loadFixture() {
        try (InputStream input = Thread.currentThread()
                .getContextClassLoader().getResourceAsStream(
                        "agent/qfq-as-of-engine-v1-golden-scenarios.json")) {
            if (input == null) {
                throw new IllegalStateException("missing QFQ golden fixture");
            }
            return MAPPER.readTree(input);
        } catch (IOException error) {
            throw new UncheckedIOException(error);
        }
    }

    private static QfqSourceIdentities identities(
            JsonNode input,
            JsonNode defaults
    ) {
        JsonNode fallback = defaults.path("sourceIdentities");
        JsonNode override = input.path("sourceIdentities");
        return new QfqSourceIdentities(
                resolveText(override, fallback, "rawSourceIdentity"),
                resolveText(override, fallback, "factorSourceIdentity"),
                resolveText(override, fallback, "calendarSourceIdentity"),
                resolveText(
                        override, fallback,
                        "corporateActionSourceIdentity"));
    }

    private static RawDailyBarObservation raw(
            JsonNode node,
            JsonNode input,
            JsonNode defaults,
            String sourceCode,
            QfqSourceIdentities identities
    ) {
        LocalDate date = LocalDate.parse(node.path("tradeDate").asText());
        FactEnvelope envelope = envelope(
                node, input, defaults, FactType.RAW_DAILY_BAR,
                "RAW_DAILY_BAR|" + resolveText(input, defaults, "symbol")
                        + "|" + date,
                sourceCode,
                resolveText(node, null, "sourceIdentity",
                        identities.rawSourceIdentity()));
        return new RawDailyBarObservation(
                envelope,
                resolveText(input, defaults, "symbol"),
                resolveText(input, defaults, "exchange"),
                date,
                decimal(node, "open"),
                decimal(node, "high"),
                decimal(node, "low"),
                decimal(node, "close"),
                qualified(node.path("volume"), defaults.path("verifiedVolume")),
                qualified(node.path("amount"), defaults.path("verifiedAmount")),
                qualified(
                        node.path("turnoverRate"),
                        defaults.path("verifiedTurnoverRate")));
    }

    private static AdjustmentFactorObservation factor(
            JsonNode node,
            JsonNode input,
            JsonNode defaults,
            String sourceCode,
            QfqSourceIdentities identities
    ) {
        LocalDate date = LocalDate.parse(
                node.path("factorEffectiveTradeDate").asText());
        FactEnvelope envelope = envelope(
                node, input, defaults, FactType.ADJUSTMENT_FACTOR,
                "ADJUSTMENT_FACTOR|"
                        + resolveText(input, defaults, "symbol")
                        + "|QFQ|" + date,
                sourceCode,
                resolveText(node, null, "sourceIdentity",
                        identities.factorSourceIdentity()));
        return new AdjustmentFactorObservation(
                envelope,
                resolveText(input, defaults, "symbol"),
                date,
                PitMarketFactsContracts.FACTOR_TYPE,
                PitMarketFactsContracts.FACTOR_COVERAGE_MODE,
                decimal(node, "factor"));
    }

    private static TradingCalendarObservation calendar(
            JsonNode node,
            JsonNode input,
            JsonNode defaults,
            String sourceCode,
            QfqSourceIdentities identities
    ) {
        LocalDate date = LocalDate.parse(node.path("calendarDate").asText());
        String exchange = resolveText(input, defaults, "exchange");
        FactEnvelope envelope = envelope(
                node, input, defaults, FactType.TRADING_CALENDAR,
                "TRADING_CALENDAR|" + exchange + "|" + date,
                sourceCode,
                resolveText(node, null, "sourceIdentity",
                        identities.calendarSourceIdentity()));
        boolean open = node.path("open").asBoolean();
        return new TradingCalendarObservation(
                envelope, exchange, date, open,
                open ? "REGULAR" : "CLOSED");
    }

    private static CorporateActionObservation action(
            JsonNode node,
            JsonNode input,
            JsonNode defaults,
            String sourceCode,
            QfqSourceIdentities identities
    ) {
        String sourceActionId = node.path("sourceActionId").asText();
        String symbol = resolveText(input, defaults, "symbol");
        FactEnvelope envelope = envelope(
                node, input, defaults, FactType.CORPORATE_ACTION,
                "CORPORATE_ACTION|" + symbol + "|" + sourceActionId,
                sourceCode,
                resolveText(node, null, "sourceIdentity",
                        identities.corporateActionSourceIdentity()));
        return new CorporateActionObservation(
                envelope,
                sourceActionId,
                symbol,
                CorporateActionType.CASH_DIVIDEND,
                nullableDate(node, "announcementDate"),
                LocalDate.parse(node.path("effectiveTradeDate").asText()),
                MAPPER.createObjectNode());
    }

    private static FactorPredecessor predecessor(
            JsonNode node,
            JsonNode input,
            JsonNode defaults,
            String sourceCode,
            QfqSourceIdentities identities
    ) {
        return new FactorPredecessor(
                node.path("observationId").asLong(),
                resolveText(node, null, "sourceCode", sourceCode),
                resolveText(node, null, "sourceIdentity",
                        identities.factorSourceIdentity()),
                resolveText(input, defaults, "symbol"),
                LocalDate.parse(
                        node.path("factorEffectiveTradeDate").asText()),
                decimal(node, "factor"),
                Instant.parse(node.path("knownAt").asText()),
                RevisionQualification.valueOf(
                        node.path("revisionQualification").asText()));
    }

    private static FactEnvelope envelope(
            JsonNode node,
            JsonNode input,
            JsonNode defaults,
            FactType factType,
            String naturalKey,
            String sourceCode,
            String sourceIdentity
    ) {
        RevisionQualification revision = RevisionQualification.valueOf(
                resolveText(node, input, defaults,
                        "revisionQualification"));
        return new FactEnvelope(
                node.path("id").asLong(),
                longValue(node, defaults.path("batchLineage"), "batchId", 1),
                factType,
                factType.contractVersion(),
                naturalKey,
                intValue(node, null, "chainSequence", 1),
                nullableLong(node, "predecessorObservationId"),
                resolveText(node, null, "sourceCode", sourceCode),
                sourceIdentity,
                resolveNullableText(
                        node, input, defaults, "providerDatasetVersion"),
                resolveNullableText(
                        node, input, defaults, "providerRevision"),
                resolveNullableText(
                        node, input, defaults, "providerSnapshotId"),
                resolveNullableInstant(
                        node, input, defaults, "providerPublishedAt"),
                resolveNullableInstant(
                        node, input, defaults, "providerUpdatedAt"),
                resolveInstant(node, input, defaults, "firstObservedAt"),
                resolveInstant(node, input, defaults, "knownAt"),
                resolveInstant(node, input, defaults, "recordedAt"),
                node.path("canonicalContentHash").asText(),
                node.path("observationVersion").asText(),
                revision,
                AssuranceLevel.valueOf(resolveText(
                        node, input, defaults, "assuranceLevel")),
                UsageQualification.valueOf(resolveText(
                        node, input, defaults, "usageQualification")),
                resolveBoolean(node, input, defaults, "formalEligible"),
                resolveBoolean(
                        node, input, defaults, "localPersistenceAllowed"),
                resolveBoolean(
                        node, input, defaults, "historicalReplayAllowed"),
                resolveBoolean(node, input, defaults, "backtestAllowed"),
                resolveBoolean(node, input, defaults, "agentUseAllowed"),
                MAPPER.createObjectNode());
    }

    private static BatchLineage batchLineage(
            JsonNode defaults,
            String sourceCode
    ) {
        JsonNode node = defaults.path("batchLineage");
        return new BatchLineage(
                node.path("batchVersion").asText(),
                node.path("datasetVersion").asText(),
                nullableText(node.path("providerDatasetVersion")),
                RunNamespace.valueOf(node.path("runNamespace").asText()),
                sourceCode,
                node.path("requestSourceIdentity").asText(),
                RevisionQualification.valueOf(
                        node.path("revisionQualification").asText()),
                AssuranceLevel.valueOf(
                        node.path("assuranceLevel").asText()),
                UsageQualification.valueOf(
                        node.path("usageQualification").asText()),
                Instant.parse(node.path("observedAt").asText()),
                node.path("responseComplete").asBoolean());
    }

    private static QualifiedMarketField qualified(
            JsonNode override,
            JsonNode fallback
    ) {
        JsonNode node = override.isMissingNode() ? fallback : override;
        String value = nullableText(node.path("value"));
        return new QualifiedMarketField(
                value == null ? null : new BigDecimal(value),
                FieldQualification.valueOf(
                        node.path("qualification").asText()),
                MarketFieldUnit.valueOf(node.path("unitCode").asText()),
                MarketFieldSemantic.valueOf(
                        node.path("semanticCode").asText()));
    }

    private static <T> List<T> observations(
            JsonNode array,
            Function<JsonNode, T> mapper
    ) {
        List<T> result = new ArrayList<>();
        array.forEach(node -> result.add(mapper.apply(node)));
        return result;
    }

    private static <T> List<T> selectVisible(
            List<T> values,
            Instant cutoff,
            Function<T, Object> naturalKey
    ) {
        Map<Object, T> selected = new LinkedHashMap<>();
        for (T value : values) {
            FactEnvelope envelope = envelope(value);
            if (envelope.knownAt().isAfter(cutoff)) {
                continue;
            }
            selected.merge(
                    naturalKey.apply(value),
                    value,
                    (left, right) -> envelopeOrder()
                            .compare(envelope(left), envelope(right)) >= 0
                            ? left : right);
        }
        return selected.values().stream()
                .sorted(Comparator.comparing(
                        value -> naturalKey.apply(value).toString()))
                .toList();
    }

    private static Comparator<FactEnvelope> envelopeOrder() {
        return Comparator
                .comparingInt((FactEnvelope value) ->
                        qualificationRank(value.revisionQualification()))
                .thenComparing(FactEnvelope::knownAt)
                .thenComparingInt(FactEnvelope::chainSequence)
                .thenComparingLong(FactEnvelope::id);
    }

    private static int qualificationRank(
            RevisionQualification qualification
    ) {
        return switch (qualification) {
            case PROVIDER_VERIFIED -> 4;
            case SYSTEM_KNOWLEDGE_ONLY -> 3;
            case PROVIDER_UNVERIFIED -> 2;
            case PROVIDER_UNAVAILABLE -> 1;
        };
    }

    private static FactEnvelope envelope(Object value) {
        if (value instanceof RawDailyBarObservation item) {
            return item.envelope();
        }
        if (value instanceof AdjustmentFactorObservation item) {
            return item.envelope();
        }
        if (value instanceof TradingCalendarObservation item) {
            return item.envelope();
        }
        if (value instanceof CorporateActionObservation item) {
            return item.envelope();
        }
        throw new IllegalArgumentException("unsupported observation");
    }

    private static ObjectNode project(QfqAsOfResult result) {
        ObjectNode projected = MAPPER.createObjectNode();
        projected.put("available", result.available());
        if (result.reasonCode() == null) {
            projected.putNull("reasonCode");
        } else {
            projected.put("reasonCode", result.reasonCode());
        }
        putDate(
                projected, "requestEffectiveTradeDate",
                result.requestEffectiveTradeDate());
        putDate(projected, "anchorTradeDate", result.anchorTradeDate());
        ArrayNode bars = projected.putArray("bars");
        result.bars().forEach(bar -> {
            ObjectNode item = bars.addObject();
            item.put("tradeDate", bar.tradeDate().toString());
            item.put("open", bar.open().toPlainString());
            item.put("high", bar.high().toPlainString());
            item.put("low", bar.low().toPlainString());
            item.put("close", bar.close().toPlainString());
            item.put(
                    "rawObservationVersion",
                    bar.rawObservationVersion());
            item.put(
                    "factorObservationVersion",
                    bar.factorObservationVersion());
        });
        ObjectNode lineage = projected.putObject("lineage");
        addVersions(
                lineage.putArray("raw"),
                result.rawLineage().stream()
                        .map(item -> item.envelope().observationVersion())
                        .toList());
        addVersions(
                lineage.putArray("factor"),
                result.factorLineage().stream()
                        .map(item -> item.envelope().observationVersion())
                        .toList());
        addVersions(
                lineage.putArray("calendar"),
                result.calendarLineage().stream()
                        .map(item -> item.envelope().observationVersion())
                        .toList());
        addVersions(
                lineage.putArray("corporateAction"),
                result.corporateActionLineage().stream()
                        .map(item -> item.envelope().observationVersion())
                        .toList());
        return projected;
    }

    private static void addVersions(ArrayNode target, List<String> values) {
        values.forEach(target::add);
    }

    private static void putDate(
            ObjectNode node,
            String field,
            LocalDate value
    ) {
        if (value == null) {
            node.putNull(field);
        } else {
            node.put(field, value.toString());
        }
    }

    private static BigDecimal decimal(JsonNode node, String field) {
        return new BigDecimal(node.path(field).asText());
    }

    private static LocalDate nullableDate(JsonNode node, String field) {
        JsonNode value = node.path(field);
        return value.isMissingNode() || value.isNull()
                ? null : LocalDate.parse(value.asText());
    }

    private static Long nullableLong(JsonNode node, String field) {
        JsonNode value = node.path(field);
        return value.isMissingNode() || value.isNull()
                ? null : value.asLong();
    }

    private static long longValue(
            JsonNode primary,
            JsonNode fallback,
            String field,
            long defaultValue
    ) {
        JsonNode value = resolve(primary, fallback, null, field);
        return value == null || value.isNull() ? defaultValue : value.asLong();
    }

    private static int intValue(
            JsonNode primary,
            JsonNode fallback,
            String field,
            int defaultValue
    ) {
        JsonNode value = resolve(primary, fallback, null, field);
        return value == null || value.isNull() ? defaultValue : value.asInt();
    }

    private static String resolveText(
            JsonNode primary,
            JsonNode fallback,
            String field
    ) {
        JsonNode value = resolve(primary, fallback, null, field);
        if (value == null || value.isNull() || value.asText().isBlank()) {
            throw new IllegalArgumentException("missing " + field);
        }
        return value.asText();
    }

    private static String resolveText(
            JsonNode primary,
            JsonNode fallback,
            String field,
            String defaultValue
    ) {
        JsonNode value = resolve(primary, fallback, null, field);
        return value == null || value.isNull()
                ? defaultValue : value.asText();
    }

    private static String resolveText(
            JsonNode first,
            JsonNode second,
            JsonNode third,
            String field
    ) {
        JsonNode value = resolve(first, second, third, field);
        if (value == null || value.isNull() || value.asText().isBlank()) {
            throw new IllegalArgumentException("missing " + field);
        }
        return value.asText();
    }

    private static String resolveNullableText(
            JsonNode first,
            JsonNode second,
            JsonNode third,
            String field
    ) {
        JsonNode value = resolve(first, second, third, field);
        return nullableText(value);
    }

    private static Instant resolveInstant(
            JsonNode first,
            JsonNode second,
            JsonNode third,
            String field
    ) {
        return Instant.parse(resolveText(first, second, third, field));
    }

    private static Instant resolveNullableInstant(
            JsonNode first,
            JsonNode second,
            JsonNode third,
            String field
    ) {
        String value = resolveNullableText(first, second, third, field);
        return value == null ? null : Instant.parse(value);
    }

    private static boolean resolveBoolean(
            JsonNode first,
            JsonNode second,
            JsonNode third,
            String field
    ) {
        JsonNode value = resolve(first, second, third, field);
        if (value == null || value.isNull()) {
            throw new IllegalArgumentException("missing " + field);
        }
        return value.asBoolean();
    }

    private static JsonNode resolve(
            JsonNode first,
            JsonNode second,
            JsonNode third,
            String field
    ) {
        for (JsonNode node : List.of(
                first == null ? MAPPER.missingNode() : first,
                second == null ? MAPPER.missingNode() : second,
                third == null ? MAPPER.missingNode() : third)) {
            if (node.has(field)) {
                return node.get(field);
            }
        }
        return null;
    }

    private static String nullableText(JsonNode value) {
        return value == null || value.isMissingNode() || value.isNull()
                ? null : value.asText();
    }
}
