package com.stockquant.server.agent.marketfacts;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.HexFormat;
import java.util.Objects;
import java.util.Properties;

/** Verifies the sidecar generated by the controlled clean-build script. */
public final class TushareControlledAcceptanceBuildProof {
    private TushareControlledAcceptanceBuildProof() {
    }

    public static VerifiedBuildProof loadControlledArtifact(
            Path artifact,
            Path proofSidecar
    ) {
        Objects.requireNonNull(artifact, "artifact");
        Objects.requireNonNull(proofSidecar, "proofSidecar");
        if (!Files.isRegularFile(artifact) || !Files.isRegularFile(proofSidecar)) {
            throw invalid("TUSHARE_CONTROLLED_ACCEPTANCE_BUILD_PROOF_MISSING");
        }
        Properties properties = new Properties();
        try (InputStream input = Files.newInputStream(proofSidecar)) {
            properties.load(input);
        } catch (IOException error) {
            throw invalid("TUSHARE_CONTROLLED_ACCEPTANCE_BUILD_PROOF_UNREADABLE");
        }
        String actualArtifactSha = sha256(artifact);
        VerifiedBuildProof proof = new VerifiedBuildProof(
                properties.getProperty("git.commit"),
                Boolean.parseBoolean(properties.getProperty("git.trackedClean")),
                actualArtifactSha,
                properties.getProperty("artifact.sha256"),
                Instant.parse(properties.getProperty("build.time")),
                properties.getProperty("java.version"),
                properties.getProperty("module.version"),
                properties.getProperty("executor.version"),
                properties.getProperty("qualification.rule.version"),
                ProofSource.CONTROLLED_BUILD_ARTIFACT);
        proof.validate();
        return proof;
    }

    static VerifiedBuildProof verifiedTestProof(
            String gitCommit,
            String artifactSha256
    ) {
        return new VerifiedBuildProof(
                gitCommit, true, artifactSha256, artifactSha256,
                Instant.parse("2026-08-01T00:00:00Z"),
                "17-test", "1.4.0-test",
                TushareControlledAcceptanceExecution.EXECUTOR_VERSION,
                TushareControlledAcceptanceExecution.RULE_VERSION,
                ProofSource.TEST_ONLY);
    }

    public static final class VerifiedBuildProof {
        private final String gitCommit;
        private final boolean trackedWorkspaceClean;
        private final String actualArtifactSha256;
        private final String declaredArtifactSha256;
        private final Instant buildTime;
        private final String javaVersion;
        private final String moduleVersion;
        private final String executorVersion;
        private final String qualificationRuleVersion;
        private final ProofSource source;

        private VerifiedBuildProof(
                String gitCommit,
                boolean trackedWorkspaceClean,
                String actualArtifactSha256,
                String declaredArtifactSha256,
                Instant buildTime,
                String javaVersion,
                String moduleVersion,
                String executorVersion,
                String qualificationRuleVersion,
                ProofSource source
        ) {
            this.gitCommit = TushareControlledAcceptanceExecution.commit(gitCommit);
            this.trackedWorkspaceClean = trackedWorkspaceClean;
            this.actualArtifactSha256 = TushareControlledAcceptanceExecution.sha256(actualArtifactSha256);
            this.declaredArtifactSha256 = TushareControlledAcceptanceExecution.sha256(declaredArtifactSha256);
            this.buildTime = Objects.requireNonNull(buildTime, "buildTime");
            this.javaVersion = TushareControlledAcceptanceExecution.safeText(javaVersion);
            this.moduleVersion = TushareControlledAcceptanceExecution.safeText(moduleVersion);
            this.executorVersion = TushareControlledAcceptanceExecution.safeText(executorVersion);
            this.qualificationRuleVersion = TushareControlledAcceptanceExecution.safeText(qualificationRuleVersion);
            this.source = Objects.requireNonNull(source, "source");
        }

        void validate() {
            if (!trackedWorkspaceClean
                    || !actualArtifactSha256.equals(declaredArtifactSha256)
                    || !TushareControlledAcceptanceExecution.EXECUTOR_VERSION.equals(executorVersion)
                    || !TushareControlledAcceptanceExecution.RULE_VERSION.equals(qualificationRuleVersion)) {
                throw invalid("TUSHARE_CONTROLLED_ACCEPTANCE_BUILD_PROOF_INVALID");
            }
        }

        boolean governanceEligible() {
            validate();
            return source == ProofSource.CONTROLLED_BUILD_ARTIFACT;
        }

        public String gitCommit() { return gitCommit; }
        public boolean trackedWorkspaceClean() { return trackedWorkspaceClean; }
        public String actualArtifactSha256() { return actualArtifactSha256; }
        public String declaredArtifactSha256() { return declaredArtifactSha256; }
        public Instant buildTime() { return buildTime; }
        public String javaVersion() { return javaVersion; }
        public String moduleVersion() { return moduleVersion; }
        public String executorVersion() { return executorVersion; }
        public String qualificationRuleVersion() { return qualificationRuleVersion; }
        public ProofSource source() { return source; }
    }

    public enum ProofSource {
        CONTROLLED_BUILD_ARTIFACT,
        TEST_ONLY
    }

    private static String sha256(Path artifact) {
        try (InputStream input = Files.newInputStream(artifact)) {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] buffer = new byte[8192];
            int read;
            while ((read = input.read(buffer)) >= 0) {
                digest.update(buffer, 0, read);
            }
            return HexFormat.of().formatHex(digest.digest());
        } catch (IOException | NoSuchAlgorithmException error) {
            throw invalid("TUSHARE_CONTROLLED_ACCEPTANCE_ARTIFACT_HASH_FAILED");
        }
    }

    private static IllegalArgumentException invalid(String code) {
        return new IllegalArgumentException(code);
    }
}
